### ISSUE TITLE
Error since the last update

### ISSUE THREAD

**Issue by cnoceda** [stumpwm/stumpwm#1201]
Hi,
I update from the repo this morning and compile with SBCL 2.4.7 and I've the following error.
`Unhandled XLIB::UNIMPLEMENTED-EVENT in thread #<SB-THREAD:THREAD tid=2485 "main thread" RUNNING
                                                 {10013A0003}>:
  Event code 0 not implemented for display #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)>

Backtrace for: #<SB-THREAD:THREAD tid=2485 "main thread" RUNNING {10013A0003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<XLIB::UNIMPLEMENTED-EVENT {10018FE503}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<XLIB::UNIMPLEMENTED-EVENT {10018FE503}>)
2: (INVOKE-DEBUGGER #<XLIB::UNIMPLEMENTED-EVENT {10018FE503}>)
3: (CERROR "Ignore the event" XLIB::UNIMPLEMENTED-EVENT :EVENT-CODE 0 :DISPLAY #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)>)
4: (XLIB::GET-INTERNAL-EVENT-CODE #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)> 50)
5: (XLIB::READ-EVENT-INPUT #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)> 50 #S(XLIB::REPLY-BUFFER :SIZE 32 :IBUF8 #(50 62 0 0 37 0 0 0 66 105 0 0 ...) :NEXT NIL :DATA-SIZE 32))
6: (XLIB::READ-INPUT #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)> NIL NIL #<FUNCTION (LAMBDA (XLIB::PENDING-COMMAND) :IN XLIB::READ-REPLY) {B80018378B}> #S(XLIB::PENDING-COMMAND :SEQUENCE 17 :REPLY-BUFFER NIL :PROCESS #<SB-THREAD:THREAD tid=2485 "main thread" RUNNING {10013A0003}> :NEXT NIL))
7: (XLIB::READ-REPLY #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)> #S(XLIB::PENDING-COMMAND :SEQUENCE 17 :REPLY-BUFFER NIL :PROCESS #<SB-THREAD:THREAD tid=2485 "main thread" RUNNING {10013A0003}> :NEXT NIL))
8: (XLIB:KEYBOARD-MAPPING #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)> :FIRST-KEYCODE NIL :START NIL :END NIL :DATA NIL)
9: (XLIB::DISPLAY-KEYBOARD-MAPPING #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)>)
10: (XLIB:KEYSYM->KEYCODES #<XLIB:DISPLAY :0 (The X.Org Foundation R12101013)> 65511)
11: ((LABELS STUMPWM::FIND-MOD :IN STUMPWM::GET-MODIFIER-MAP) "Meta_L" NIL)
12: (STUMPWM::GET-MODIFIER-MAP)
13: (STUMPWM::UPDATE-MODIFIER-MAP)
14: (STUMPWM::STUMPWM-INTERNAL ":0")
15: (STUMPWM:STUMPWM ":0")
16: ((LAMBDA NIL :IN "/home/XXXXXX/src/stumpwm/make-image.lisp"))
17: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
18: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
19: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting`
Has someone this error?
Thancls in advance.

**Comment by cnoceda** [comment]
I roll back the repo, and the error still there, so probably is with sbcl ¿? I'm using Void.

**Comment by DerGuteMoritz** [comment]
Same here on NixOS unstable on which I just received an update from SBCL 2.4.5 to 2.4.7 and ended up with the same error.

**Comment by czerw** [comment]
I faced the same issue on openSUSE Tumbleweed after sbcl update to 2.4.7. It works fine if sbcl is downgraded to version 2.4.6.

**Comment by metayan** [comment]
This is fixed in https://github.com/sharplispers/clx/pull/205 , so until a newer `quicklisp` than version 2023-10-21 is released, the solution is to use a newer `clx` than is currently in `quicklisp` by cloning `clx` into `local-projects` with something like
```
cd ~/quicklisp/local-projects
git clone https://github.com/sharplispers/clx
sbcl --eval '(ql:register-local-projects)' --quit
```
and then rebuilding or reloading `stumpwm`.

This issue appears from [sbcl-2.4.6-103-g9e354f04e](https://github.com/sbcl/sbcl/commit/9e354f04e583a7190118cdaa371b76fae657a5d2), when SBCL's `read-sequence` was corrected.

`clx` from 0.7.6 handles this and works with SBCL 2.4.6 as well.

**Comment by cnoceda** [comment]
@metayan Thanks!! It works perfect for me.

**Comment by rand00** [comment]
> This is fixed in [sharplispers/clx#205](https://github.com/sharplispers/clx/pull/205) , so until a newer `quicklisp` than version 2023-10-21 is released, the solution is to use a newer `clx` than is currently in `quicklisp` by cloning `clx` into `local-projects` with something like
> 
> ```
> cd ~/quicklisp/local-projects
> git clone https://github.com/sharplispers/clx
> sbcl --eval '(ql:register-local-projects)' --quit
> ```
> 
> and then rebuilding or reloading `stumpwm`.
> 
> This issue appears from [sbcl-2.4.6-103-g9e354f04e](https://github.com/sbcl/sbcl/commit/9e354f04e583a7190118cdaa371b76fae657a5d2), when SBCL's `read-sequence` was corrected.
> 
> `clx` from 0.7.6 handles this and works with SBCL 2.4.6 as well.

I tried to apply this fix before `make clean` and then the usual `autogent.sh; configure; make`, but it didn't fix it for me. Got it working by downgrading `sbcl` to 2.4.6-1.

**Comment by MIvanchev** [comment]
Can someone retest this with current SBCL and CLX?
