### ISSUE TITLE
Error In Command 'redisplay': The value NIL is not of type XLIB:WM-SIZE-HINTS

### ISSUE THREAD

**Issue by PuercoPop** [stumpwm/stumpwm#820]
To reproduce open random image with `feh` and execute `redisplay` produces this error message:
```text
Error In Command 'redisplay': The value
                                           NIL
                                         is not of type
                                           XLIB:WM-SIZE-HINTS
```

Also `feh` repeats the image file because I guess it doesn't know corrently width and height of the window. To reproduce this issue:
* Open random file with `feh`. It repeats the image both vertically and horizontally. 
* Split the screen horizontally or vertically (`vsplit` / `hsplit`)
* Return back to single window (`only`).
* Now `feh` shows image without repeats.

Screenshot feh repeating issue:
![ksnip_20201006-124307](https://user-images.githubusercontent.com/5196786/95186235-73aa4f80-07d2-11eb-872b-88c6c449189c.png)

My StumpWM version is = `19.11 Compiled On Tue Sep 29 2020 18:39:46`
My feh version is = `feh version 3.5
Compile-time switches: curl exif verscmp xinerama`

Related issue from another window manager: https://github.com/swaywm/sway/issues/3106

_Originally posted by @erenhatirnaz in https://github.com/stumpwm/stumpwm/issues/775#issuecomment-704162690_

**Comment by erenhatirnaz** [comment]
`redisplay` issue seems fixed (doesn't throwing an error message) for `feh` but now other GTK based applications (I tested on firefox and nautilus) throws this message when execute `redisplay`:
```text
Error In Command 'redisplay': The value
                                           NIL
                                         is not of type
                                           NUMBER
                                         when binding SB-KERNEL::Y
```

and when the' feh` window is created for the first time, the repeating problem seems to be unresolved. The repeating issue is solved only when the `redisplay` command is executed in the `feh` window.

StumpWM version= `19.11-184-g1305528 Compiled On Thu Oct 08 2020 10:02:09`
I'm on up-to-date master branch. 

![ksnip_20201008-100848](https://user-images.githubusercontent.com/5196786/95427439-408dca80-0950-11eb-8f3f-bae9c525c9c0.png)

**Comment by PuercoPop** [comment]
@erenhatirnaz It should be fixed now. Checked with nautilus at least.

**Comment by erenhatirnaz** [comment]
Yes. The `redisplay` issue seems fixed for both firefox and nautilus.
But repeating issue still continues in `feh`. Is the repetition problem caused by something else? I don't understand why `feh` still repeating the image.

**Comment by CatherineTower** [comment]
I'm having the same thing happen when I open a small image in `feh`. If I run `redisplay` it stops tiling, which leads me to believe that `redisplay` does something that opening a window doesn't. I'm having a look at what that might be, but please let me know if I'm on completely the wrong track

**Comment by erenhatirnaz** [comment]
@CatherineTower You're definitely on right track. I'm having same situation.

**Comment by MIvanchev** [comment]
Could someone retest this.
